global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'  # Changed

scrape_configs:
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']  # Changed

  - job_name: 'my-service'
    static_configs:
      - targets: ['localhost:8080']  # Change this too

